In [22]:
import matplotlib.pyplot as plt

In [21]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import categorical_crossentropy
from tensorflow.keras.utils import to_categorical
import numpy as np
import cv2


In [39]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()


((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [40]:
x_train = x_train.reshape(-1, 784)
x_test = x_test.reshape(-1, 784)



array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [42]:
y_train = to_categorical(y_train, num_classes=10)

y_test = to_categorical(y_test, num_classes=10)



[[[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[0. 1. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 ...

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]]


In [57]:
model = tf.keras.models.load_model('model.h5')

In [65]:
id_test = 100
img = x_test[id_test, :].reshape(1, -1)
label = np.argmax(y_test[id_test, :])
print(img)


[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0 127 221  52   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0  64 229 219 104   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0  13 235 140   4
    3   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0 118 227  25   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 236 133
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0  13 243  93   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  85
  243  21   0   0   0   0   0   0   0 

In [64]:
predict = model.predict()[0]
predict = np.argmax(predict)
print("ket qua du doan: " + str(predict))
plt.imshow(img.reshape(28, 28), cmap='gray')


TypeError: predict() missing 1 required positional argument: 'x'

In [4]:
model = tf.keras.models.load_model('model.h5')


array([[[84,  1, 68],
        [84,  1, 68],
        [84,  1, 68],
        ...,
        [84,  1, 68],
        [84,  1, 68],
        [84,  1, 68]],

       [[84,  1, 68],
        [84,  1, 68],
        [84,  1, 68],
        ...,
        [84,  1, 68],
        [84,  1, 68],
        [84,  1, 68]],

       [[84,  1, 68],
        [84,  1, 68],
        [84,  1, 68],
        ...,
        [84,  1, 68],
        [84,  1, 68],
        [84,  1, 68]],

       ...,

       [[84,  1, 68],
        [84,  1, 68],
        [84,  1, 68],
        ...,
        [84,  1, 68],
        [84,  1, 68],
        [84,  1, 68]],

       [[84,  1, 68],
        [84,  1, 68],
        [84,  1, 68],
        ...,
        [84,  1, 68],
        [84,  1, 68],
        [84,  1, 68]],

       [[84,  1, 68],
        [84,  1, 68],
        [84,  1, 68],
        ...,
        [84,  1, 68],
        [84,  1, 68],
        [84,  1, 68]]], dtype=uint8)

In [12]:
predict = model.predict(img)[0]
predict = np.argmax(predict)
print("ket qua du doan: " + str(predict))
plt.imshow(img.reshape(28, 28), cmap='gray')


ValueError: in user code:

    C:\Users\nguye\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\training.py:1587 predict_function  *
        return step_function(self, iterator)
    C:\Users\nguye\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\training.py:1577 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\nguye\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\training.py:1570 run_step  **
        outputs = model.predict_step(data)
    C:\Users\nguye\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\training.py:1538 predict_step
        return self(x, training=False)
    C:\Users\nguye\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\utils\traceback_utils.py:67 error_handler
        raise e.with_traceback(filtered_tb) from None
    C:\Users\nguye\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\input_spec.py:263 assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" is '

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 784), found shape=(None, 2352)
